# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1142, 726)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resource/icon1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:rgb(231, 231, 231)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.video_handle = QtWidgets.QLabel(self.centralwidget)
        self.video_handle.setEnabled(True)
        self.video_handle.setMinimumSize(QtCore.QSize(512, 512))
        self.video_handle.setMaximumSize(QtCore.QSize(512, 512))
        self.video_handle.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;")
        self.video_handle.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.video_handle.setLineWidth(5)
        self.video_handle.setMidLineWidth(5)
        self.video_handle.setText("")
        self.video_handle.setObjectName("video_handle")
        self.gridLayout.addWidget(self.video_handle, 0, 2, 1, 1)
        self.video_orign = QtWidgets.QLabel(self.centralwidget)
        self.video_orign.setEnabled(True)
        self.video_orign.setMinimumSize(QtCore.QSize(512, 512))
        self.video_orign.setMaximumSize(QtCore.QSize(512, 512))
        self.video_orign.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;")
        self.video_orign.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.video_orign.setFrameShadow(QtWidgets.QFrame.Plain)
        self.video_orign.setLineWidth(5)
        self.video_orign.setMidLineWidth(5)
        self.video_orign.setText("")
        self.video_orign.setObjectName("video_orign")
        self.gridLayout.addWidget(self.video_orign, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.process = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.process.sizePolicy().hasHeightForWidth())
        self.process.setSizePolicy(sizePolicy)
        self.process.setMinimumSize(QtCore.QSize(500, 30))
        self.process.setMaximumSize(QtCore.QSize(500, 30))
        self.process.setOrientation(QtCore.Qt.Horizontal)
        self.process.setObjectName("process")
        self.gridLayout_5.addWidget(self.process, 0, 1, 1, 1)
        self.total_num = QtWidgets.QLabel(self.centralwidget)
        self.total_num.setMinimumSize(QtCore.QSize(100, 30))
        self.total_num.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.total_num.setFont(font)
        self.total_num.setStyleSheet("background-color: rgb(236, 236, 236)")
        self.total_num.setText("")
        self.total_num.setObjectName("total_num")
        self.gridLayout_5.addWidget(self.total_num, 0, 0, 1, 1)
        self.cur_num = QtWidgets.QLabel(self.centralwidget)
        self.cur_num.setMinimumSize(QtCore.QSize(100, 30))
        self.cur_num.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.cur_num.setFont(font)
        self.cur_num.setStyleSheet("background-color: rgb(236, 236, 236)")
        self.cur_num.setText("")
        self.cur_num.setObjectName("cur_num")
        self.gridLayout_5.addWidget(self.cur_num, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.close = QtWidgets.QPushButton(self.centralwidget)
        self.close.setMinimumSize(QtCore.QSize(80, 40))
        self.close.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.close.setFont(font)
        self.close.setStyleSheet("QPushButton{\n"
"background-color: #c8ba90;\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:#a69b78;\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"}")
        self.close.setObjectName("close")
        self.gridLayout_2.addWidget(self.close, 2, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setMinimumSize(QtCore.QSize(80, 40))
        self.start.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.start.setFont(font)
        self.start.setStyleSheet("QPushButton{\n"
"background-color: #c8ba90;\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:#a69b78;\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"}")
        self.start.setObjectName("start")
        self.gridLayout_2.addWidget(self.start, 1, 0, 1, 1)
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        self.pause.setMinimumSize(QtCore.QSize(80, 40))
        self.pause.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pause.setFont(font)
        self.pause.setStyleSheet("QPushButton{\n"
"background-color: #c8ba90;\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:#a69b78;\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"}")
        self.pause.setAutoDefault(False)
        self.pause.setObjectName("pause")
        self.gridLayout_2.addWidget(self.pause, 1, 1, 1, 1)
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setEnabled(True)
        self.open.setMinimumSize(QtCore.QSize(80, 40))
        self.open.setMaximumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.open.setFont(font)
        self.open.setMouseTracking(False)
        self.open.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.open.setAcceptDrops(False)
        self.open.setStyleSheet("QPushButton{\n"
"background-color: #c8ba90;\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:#a69b78;\n"
"border-radius: 10px;\n"
"border: 2px groove gray;\n"
"border-style: outset;\n"
"}")
        self.open.setCheckable(False)
        self.open.setChecked(False)
        self.open.setObjectName("open")
        self.gridLayout_2.addWidget(self.open, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile_F = QtWidgets.QMenu(self.menubar)
        self.menuFile_F.setObjectName("menuFile_F")
        self.menuQuit_Q = QtWidgets.QMenu(self.menubar)
        self.menuQuit_Q.setObjectName("menuQuit_Q")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMinimumSize(QtCore.QSize(800, 20))
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_start = QtWidgets.QAction(MainWindow)
        self.action_start.setObjectName("action_start")
        self.action_pause = QtWidgets.QAction(MainWindow)
        self.action_pause.setObjectName("action_pause")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.menuFile_F.addAction(self.action_open)
        self.menuFile_F.addAction(self.action_start)
        self.menuFile_F.addAction(self.action_pause)
        self.menuFile_F.addAction(self.action_close)
        self.menuQuit_Q.addAction(self.action_quit)
        self.menubar.addAction(self.menuFile_F.menuAction())
        self.menubar.addAction(self.menuQuit_Q.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "颈动脉斑块视频分割"))
        self.close.setText(_translate("MainWindow", "清除"))
        self.start.setText(_translate("MainWindow", "开始"))
        self.pause.setText(_translate("MainWindow", "暂停"))
        self.open.setText(_translate("MainWindow", "打开文件"))
        self.menuFile_F.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menuQuit_Q.setTitle(_translate("MainWindow", "其他(&E)"))
        self.action_open.setText(_translate("MainWindow", "打开文件(&O)"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_start.setText(_translate("MainWindow", "开始(&S)"))
        self.action_start.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_pause.setText(_translate("MainWindow", "暂停/继续(&P)"))
        self.action_pause.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.action_close.setText(_translate("MainWindow", "清除(&C)"))
        self.action_close.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.action_quit.setText(_translate("MainWindow", "退出(&Q)"))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
